' <auto-generated />
Imports System
Imports BilYon
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.VisualBasic

Namespace Global.BilYon.Migrations
    <DbContext(GetType(AppDbContext))>
    <Migration("20240511142451_Init")>
    Partial Class Init
        ''' <inheritdoc />
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4")

            modelBuilder.Entity("BilYon.CompDetail",
                Sub(b)
                    b.Property(Of String)("GUID").
                        HasMaxLength(36).
                        HasColumnType("TEXT")

                    b.Property(Of Integer)("BatteryLevel").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("BatteryStatus").
                        HasColumnType("TEXT")

                    b.Property(Of String)("CPU_Cores").
                        HasColumnType("TEXT")

                    b.Property(Of String)("CPU_Model").
                        HasColumnType("TEXT")

                    b.Property(Of String)("CPU_Util").
                        HasColumnType("TEXT")

                    b.Property(Of String)("CurrentUserName").
                        HasColumnType("TEXT")

                    b.Property(Of String)("CurrentUserType").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Drives").
                        HasColumnType("TEXT")

                    b.Property(Of String)("FocusedApplicationName").
                        HasColumnType("TEXT")

                    b.Property(Of String)("GPUModel").
                        HasColumnType("TEXT")

                    b.Property(Of String)("InstalledPrograms").
                        HasColumnType("TEXT")

                    b.Property(Of String)("MotherboardModel").
                        HasColumnType("TEXT")

                    b.Property(Of String)("NetworkInterfaces").
                        HasColumnType("TEXT")

                    b.Property(Of String)("RAMDevice").
                        HasColumnType("TEXT")

                    b.Property(Of Single)("RAMUtilization").
                        HasColumnType("REAL")

                    b.Property(Of Date)("RTCTime").
                        HasColumnType("TEXT")

                    b.Property(Of String)("RunningPrograms").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Screens").
                        HasColumnType("TEXT")

                    b.Property(Of TimeSpan)("Uptime").
                        HasColumnType("TEXT")

                    b.Property(Of String)("WindowsRegionLanguage").
                        HasColumnType("TEXT")

                    b.Property(Of String)("WindowsVersion").
                        HasColumnType("TEXT")

                    b.HasKey("GUID")

                    b.ToTable("CompDetail")
                End Sub)

            modelBuilder.Entity("BilYon.Computers",
                Sub(b)
                    b.Property(Of String)("GUID").
                        HasMaxLength(36).
                        HasColumnType("TEXT")

                    b.Property(Of String)("Host_Name").
                        IsRequired().
                        HasMaxLength(50).
                        HasColumnType("TEXT")

                    b.Property(Of String)("Local_Ip").
                        IsRequired().
                        HasMaxLength(15).
                        HasColumnType("TEXT")

                    b.Property(Of String)("Mac_Adress").
                        IsRequired().
                        HasMaxLength(17).
                        HasColumnType("TEXT")

                    b.HasKey("GUID")

                    b.ToTable("Computers")
                End Sub)

            modelBuilder.Entity("BilYon.LastSeen",
                Sub(b)
                    b.Property(Of Integer)("ID").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("COMP_GUID").
                        IsRequired().
                        HasMaxLength(36).
                        HasColumnType("TEXT")

                    b.Property(Of Date)("LastSeenTime").
                        HasColumnType("TEXT")

                    b.HasKey("ID")

                    b.ToTable("LastSeen")
                End Sub)

            modelBuilder.Entity("BilYon.Settings",
                Sub(b)
                    b.Property(Of String)("Setting").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Value").
                        HasColumnType("TEXT")

                    b.HasKey("Setting")

                    b.ToTable("Settings")
                End Sub)
        End Sub
    End Class
End Namespace
